name: "Run pre-commit"
description: "Install and run pre-commit with optional external config"
inputs:
  config:
    description: "Optional path or URL to a pre-commit config file"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install pre-commit
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit
      shell: bash
      run: |
        if [ -n "${{ inputs.config }}" ]; then
          pre-commit run --config "${{ inputs.config }}" --all-files --show-diff-on-failure
        else
          pre-commit run --all-files --show-diff-on-failure
        fi

