name: Config Drift Check

on:
  workflow_call:
    inputs:
      source-ref:
        description: "Ref in ci repo to fetch canonical configs"
        required: false
        default: main
        type: string

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch canonical configs
        id: fetch
        run: |
          mkdir -p _ci_configs
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/pre-commit/.pre-commit-config.yaml" -o _ci_configs/.pre-commit-config.yaml || true
          # Use strict JSON for markdownlint
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/markdownlint/.markdownlint.json" -o _ci_configs/.markdownlint.json || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/eslint.config.cjs" -o _ci_configs/eslint.config.cjs || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.stylelintrc.cjs" -o _ci_configs/.stylelintrc.cjs || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.stylelintignore" -o _ci_configs/.stylelintignore || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.prettierrc.json" -o _ci_configs/.prettierrc.json || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.prettierignore" -o _ci_configs/.prettierignore || true
          ls -la _ci_configs

      - name: Diff .pre-commit-config.yaml
        run: |
          if [ -f _ci_configs/.pre-commit-config.yaml ]; then
            if [ -f .pre-commit-config.yaml ]; then
              diff -u _ci_configs/.pre-commit-config.yaml .pre-commit-config.yaml || true
            else
              echo "NOTE: .pre-commit-config.yaml missing in repo";
            fi
          else
            echo "Canonical .pre-commit-config.yaml not found in ci repo; skipping";
          fi

      - name: Diff markdownlint config (JSON only)
        run: |
          if [ -f _ci_configs/.markdownlint.json ]; then
            if [ -f .markdownlint.json ]; then
              diff -u _ci_configs/.markdownlint.json .markdownlint.json || true
            else
              echo "NOTE: .markdownlint.json missing in repo";
            fi
          else
            echo "Canonical markdownlint JSON not found in ci repo; skipping";
          fi

      - name: Diff ESLint/Stylelint/Prettier (.ci-configs)
        run: |
          mkdir -p .ci-configs/js
          for f in eslint.config.cjs .stylelintrc.cjs .stylelintignore .prettierrc.json .prettierignore; do
            if [ -f _ci_configs/"$f" ]; then
              target=".ci-configs/js/$f"
              if [ -f "$target" ]; then
                diff -u _ci_configs/"$f" "$target" || true
              else
                echo "NOTE: $target missing in repo";
              fi
            fi
          done
