name: Config Sync PR

on:
  workflow_call:
    inputs:
      source-ref:
        description: "Ref in ci repo to fetch canonical configs"
        required: false
        default: main
        type: string
      force-pr:
        description: "差分がなくても PR を作成する（マーカーを更新）"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch canonical configs
        run: |
          mkdir -p _ci_configs
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/pre-commit/.pre-commit-config.yaml" -o _ci_configs/.pre-commit-config.yaml || true
          # Prefer strict JSON; fall back to JSONC
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/markdownlint/.markdownlint.json" -o _ci_configs/.markdownlint.json || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/markdownlint/.markdownlint.jsonc" -o _ci_configs/.markdownlint.jsonc || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/eslint.config.cjs" -o _ci_configs/eslint.config.cjs || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.stylelintrc.cjs" -o _ci_configs/.stylelintrc.cjs || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.stylelintignore" -o _ci_configs/.stylelintignore || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.prettierrc.json" -o _ci_configs/.prettierrc.json || true
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository_owner }}/ci/${{ inputs['source-ref'] }}/configs/js/.prettierignore" -o _ci_configs/.prettierignore || true

      - name: Update working tree (.ci-configs)
        id: update
        run: |
          changed=0
          if [ -f _ci_configs/.pre-commit-config.yaml ]; then
            if ! cmp -s _ci_configs/.pre-commit-config.yaml .pre-commit-config.yaml 2>/dev/null; then
              mkdir -p .
              cp _ci_configs/.pre-commit-config.yaml ./.pre-commit-config.yaml
              changed=1
            fi
          fi
          mkdir -p .ci-configs/js
          for f in eslint.config.cjs .stylelintrc.cjs .stylelintignore .prettierrc.json .prettierignore; do
            if [ -f _ci_configs/"$f" ]; then
              target=".ci-configs/js/$f"
              if ! cmp -s _ci_configs/"$f" "$target" 2>/dev/null; then
                cp _ci_configs/"$f" "$target"
                changed=1
              fi
            fi
          done
          if [ -f _ci_configs/.markdownlint.json ]; then
            if ! cmp -s _ci_configs/.markdownlint.json .markdownlint.json 2>/dev/null; then
              cp _ci_configs/.markdownlint.json ./.markdownlint.json
              changed=1
            fi
          elif [ -f _ci_configs/.markdownlint.jsonc ]; then
            # If only JSONC exists centrally, write to JSON for repos
            if ! cmp -s _ci_configs/.markdownlint.jsonc .markdownlint.jsonc 2>/dev/null; then
              cp _ci_configs/.markdownlint.jsonc ./.markdownlint.jsonc
              changed=1
            fi
          fi
          if [ "${{ inputs['force-pr'] }}" = "true" ] && [ "$changed" -eq 0 ]; then
            mkdir -p .github
            date -u +%Y-%m-%dT%H:%M:%SZ > .github/config-sync.timestamp
            changed=1
          fi
          echo "changed=${changed}" >> "$GITHUB_OUTPUT"

      - name: Cleanup temp files
        if: steps.update.outputs.changed == '1'
        run: |
          rm -rf _ci_configs || true

      - name: Create Pull Request
        if: steps.update.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/sync-ci-configs
          title: "chore(ci): 中央CI設定とのドリフトを解消"
          commit-message: |
            chore(ci): 中央CI設定とのドリフトを解消
            * .pre-commit-config.yaml / .markdownlint.jsonc を ci リポジトリに同期
          body: |
            このPRは中央CIの設定ファイルと差分が検出されたため自動作成されました。
            反映後、共有CIでのチェック内容が統一されます。
          labels: ci, chore, automation
          delete-branch: true
          auto-merge: true
          merge-method: squash

      - name: No changes detected
        if: steps.update.outputs.changed != '1'
        run: echo "No config changes detected."
