name: Web CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      run-precommit:
        required: true
        type: boolean
      deploy:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Show versions
        run: |
          node -v
          npm -v
          python -V

      - name: Check pre-commit config
        id: pc
        if: ${{ inputs['run-precommit'] }}
        shell: bash
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install pre-commit
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present == 'true' }}
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Skip pre-commit (config not found)
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present != 'true' }}
        run: echo ".pre-commit-config.yaml not found; skipping pre-commit"

      - name: Install Node deps (if package.json exists)
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Build/Test (no-op if absent)
        run: |
          if [ -f Makefile ]; then make -n build || true; fi

      - name: Deploy (placeholder)
        if: ${{ inputs.deploy }}
        run: echo "Deploy step controlled by caller workflow"
